# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xchange.proto\x12\x0cSpy.Exchange\x1a\x0c\x63ommon.proto\"a\n\nRequestBuy\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\x05\x12\x12\n\nitem_index\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x1b\n\x13is_exchange_crystal\x18\x04 \x01(\x08\"&\n\x0fRequestItemList\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\x05\"\r\n\x0bRequestList\"O\n\x0bResponseBuy\x12@\n\x16update_resource_result\x18\x02 \x01(\x0b\x32 .Spy.Common.UpdateResourceResult\"\xa6\x04\n\x10ResponseItemList\x12\x36\n\titem_list\x18\x01 \x03(\x0b\x32#.Spy.Exchange.ResponseItemList.Item\x12\r\n\x05point\x18\x02 \x01(\x05\x12\x18\n\x10\x65xchange_unit_id\x18\x03 \x01(\x05\x1a\xb8\x02\n\x04Item\x12\x12\n\nitem_index\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nneed_point\x18\x04 \x01(\x05\x12\x13\n\x0bstock_count\x18\x05 \x01(\x05\x12\x1b\n\x13\x63urrent_stock_count\x18\x06 \x01(\x05\x12\x12\n\nlabel_type\x18\x07 \x01(\x05\x12\x1a\n\x12icon_resource_type\x18\x08 \x01(\x05\x12\x18\n\x10icon_resource_id\x18\t \x01(\x05\x12G\n\x12pack_resource_list\x18\x0c \x03(\x0b\x32+.Spy.Exchange.ResponseItemList.PackResource\x12\x10\n\x08start_at\x18\r \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x0e \x01(\t\x1av\n\x0cPackResource\x12\x0f\n\x07pack_id\x18\x01 \x01(\x05\x12\x15\n\rresource_type\x18\x02 \x01(\x05\x12\x13\n\x0bresource_id\x18\x03 \x01(\x05\x12\x19\n\x11resource_value_id\x18\x04 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x05\"\xe1\x01\n\x0cResponseList\x12=\n\x0fm_exchange_list\x18\x01 \x03(\x0b\x32$.Spy.Exchange.ResponseList.MExchange\x1a\x91\x01\n\tMExchange\x12\x13\n\x0b\x65xchange_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rnew_item_flag\x18\x03 \x01(\x05\x12\x13\n\x0b\x62utton_type\x18\x04 \x01(\x05\x12\x13\n\x0b\x62\x61lloon_msg\x18\x05 \x01(\t\x12\x10\n\x08start_at\x18\x06 \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exchange_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTBUY._serialized_start=46
  _REQUESTBUY._serialized_end=143
  _REQUESTITEMLIST._serialized_start=145
  _REQUESTITEMLIST._serialized_end=183
  _REQUESTLIST._serialized_start=185
  _REQUESTLIST._serialized_end=198
  _RESPONSEBUY._serialized_start=200
  _RESPONSEBUY._serialized_end=279
  _RESPONSEITEMLIST._serialized_start=282
  _RESPONSEITEMLIST._serialized_end=832
  _RESPONSEITEMLIST_ITEM._serialized_start=400
  _RESPONSEITEMLIST_ITEM._serialized_end=712
  _RESPONSEITEMLIST_PACKRESOURCE._serialized_start=714
  _RESPONSEITEMLIST_PACKRESOURCE._serialized_end=832
  _RESPONSELIST._serialized_start=835
  _RESPONSELIST._serialized_end=1060
  _RESPONSELIST_MEXCHANGE._serialized_start=915
  _RESPONSELIST_MEXCHANGE._serialized_end=1060
# @@protoc_insertion_point(module_scope)
