# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66riend.proto\x12\nSpy.Friend\x1a\x0c\x63ommon.proto\"-\n\x13RequestCancelInvite\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\x05\"\'\n\rRequestDelete\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\x05\"A\n\x0eRequestGetList\x12\x11\n\tlist_type\x18\x01 \x01(\x05\x12\x1c\n\x14\x65xclude_user_id_list\x18\x02 \x03(\x05\"\'\n\rRequestInvite\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\x05\")\n\x0fRequestNgInvite\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\x05\")\n\x0fRequestOkInvite\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\x05\"6\n\rRequestSearch\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0cview_user_id\x18\x02 \x01(\x05\"\x0c\n\nRequestTop\"\x16\n\x14ResponseCancelInvite\"\x10\n\x0eResponseDelete\"E\n\x0fResponseGetList\x12\x32\n\x11user_profile_list\x18\x02 \x03(\x0b\x32\x17.Spy.Common.UserProfile\"\x10\n\x0eResponseInvite\"\x12\n\x10ResponseNgInvite\"\x12\n\x10ResponseOkInvite\"?\n\x0eResponseSearch\x12-\n\x0cuser_profile\x18\x01 \x01(\x0b\x32\x17.Spy.Common.UserProfile\"\xbb\x01\n\x0bResponseTop\x12\x33\n\x12t_user_friend_list\x18\x01 \x03(\x0b\x32\x17.Spy.Common.UserProfile\x12:\n\x19t_user_friend_invite_list\x18\x02 \x03(\x0b\x32\x17.Spy.Common.UserProfile\x12;\n\x1at_user_friend_invited_list\x18\x03 \x03(\x0b\x32\x17.Spy.Common.UserProfileb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'friend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCANCELINVITE._serialized_start=42
  _REQUESTCANCELINVITE._serialized_end=87
  _REQUESTDELETE._serialized_start=89
  _REQUESTDELETE._serialized_end=128
  _REQUESTGETLIST._serialized_start=130
  _REQUESTGETLIST._serialized_end=195
  _REQUESTINVITE._serialized_start=197
  _REQUESTINVITE._serialized_end=236
  _REQUESTNGINVITE._serialized_start=238
  _REQUESTNGINVITE._serialized_end=279
  _REQUESTOKINVITE._serialized_start=281
  _REQUESTOKINVITE._serialized_end=322
  _REQUESTSEARCH._serialized_start=324
  _REQUESTSEARCH._serialized_end=378
  _REQUESTTOP._serialized_start=380
  _REQUESTTOP._serialized_end=392
  _RESPONSECANCELINVITE._serialized_start=394
  _RESPONSECANCELINVITE._serialized_end=416
  _RESPONSEDELETE._serialized_start=418
  _RESPONSEDELETE._serialized_end=434
  _RESPONSEGETLIST._serialized_start=436
  _RESPONSEGETLIST._serialized_end=505
  _RESPONSEINVITE._serialized_start=507
  _RESPONSEINVITE._serialized_end=523
  _RESPONSENGINVITE._serialized_start=525
  _RESPONSENGINVITE._serialized_end=543
  _RESPONSEOKINVITE._serialized_start=545
  _RESPONSEOKINVITE._serialized_end=563
  _RESPONSESEARCH._serialized_start=565
  _RESPONSESEARCH._serialized_end=628
  _RESPONSETOP._serialized_start=631
  _RESPONSETOP._serialized_end=818
# @@protoc_insertion_point(module_scope)
