# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamecenter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gamecenter.proto\x12\x0eSpy.Gamecenter\x1a\x0c\x63ommon.proto\"\x10\n\x0eRequestGetList\"1\n\x0fResponseGetList\x12\x1e\n\x16gamecenter_id_list_all\x18\x01 \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamecenter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTGETLIST._serialized_start=50
  _REQUESTGETLIST._serialized_end=66
  _RESPONSEGETLIST._serialized_start=68
  _RESPONSEGETLIST._serialized_end=117
# @@protoc_insertion_point(module_scope)
