# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: present.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpresent.proto\x12\x0bSpy.Present\x1a\x0c\x63ommon.proto\"\x10\n\x0eRequestGetList\"\x18\n\x16RequestGetReceivedList\"(\n\x0eRequestReceive\x12\x16\n\x0epresent_box_id\x18\x01 \x01(\x05\"0\n\x11RequestReceiveAll\x12\x1b\n\x13present_box_id_list\x18\x01 \x03(\x05\"\xd6\x02\n\x0fResponseGetList\x12M\n\x17t_user_present_box_list\x18\x01 \x03(\x0b\x32,.Spy.Present.ResponseGetList.TUserPresentBox\x1a\xf3\x01\n\x0fTUserPresentBox\x12\x16\n\x0epresent_box_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\x15\n\rresource_type\x18\x04 \x01(\x05\x12\x13\n\x0bresource_id\x18\x05 \x01(\x05\x12\x19\n\x11resource_value_id\x18\x06 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x05\x12\x12\n\nlimited_at\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x13\n\x0breceived_at\x18\n \x01(\t\x12\x0f\n\x07message\x18\x0b \x01(\t\"\x83\x03\n\x17ResponseGetReceivedList\x12U\n\x17t_user_present_box_list\x18\x01 \x03(\x0b\x32\x34.Spy.Present.ResponseGetReceivedList.TUserPresentBox\x1a\x90\x02\n\x0fTUserPresentBox\x12\x16\n\x0epresent_box_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\x15\n\rresource_type\x18\x04 \x01(\x05\x12\x13\n\x0bresource_id\x18\x05 \x01(\x05\x12\x19\n\x11resource_value_id\x18\x06 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x05\x12\x12\n\nlimited_at\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x13\n\x0breceived_at\x18\n \x01(\t\x12\x1b\n\x13is_resource_replace\x18\x0b \x01(\x05\x12\x0f\n\x07message\x18\x0c \x01(\t\"S\n\x0fResponseReceive\x12@\n\x16update_resource_result\x18\n \x01(\x0b\x32 .Spy.Common.UpdateResourceResult\"s\n\x12ResponseReceiveAll\x12\x1b\n\x13present_box_id_list\x18\x01 \x03(\x05\x12@\n\x16update_resource_result\x18\x0b \x01(\x0b\x32 .Spy.Common.UpdateResourceResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'present_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTGETLIST._serialized_start=44
  _REQUESTGETLIST._serialized_end=60
  _REQUESTGETRECEIVEDLIST._serialized_start=62
  _REQUESTGETRECEIVEDLIST._serialized_end=86
  _REQUESTRECEIVE._serialized_start=88
  _REQUESTRECEIVE._serialized_end=128
  _REQUESTRECEIVEALL._serialized_start=130
  _REQUESTRECEIVEALL._serialized_end=178
  _RESPONSEGETLIST._serialized_start=181
  _RESPONSEGETLIST._serialized_end=523
  _RESPONSEGETLIST_TUSERPRESENTBOX._serialized_start=280
  _RESPONSEGETLIST_TUSERPRESENTBOX._serialized_end=523
  _RESPONSEGETRECEIVEDLIST._serialized_start=526
  _RESPONSEGETRECEIVEDLIST._serialized_end=913
  _RESPONSEGETRECEIVEDLIST_TUSERPRESENTBOX._serialized_start=641
  _RESPONSEGETRECEIVEDLIST_TUSERPRESENTBOX._serialized_end=913
  _RESPONSERECEIVE._serialized_start=915
  _RESPONSERECEIVE._serialized_end=998
  _RESPONSERECEIVEALL._serialized_start=1000
  _RESPONSERECEIVEALL._serialized_end=1115
# @@protoc_insertion_point(module_scope)
