# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregist.proto\x12\nSpy.Regist\x1a\x0c\x63ommon.proto\"\x0e\n\x0cRequestCheck\"\x0c\n\nRequestDmm\"?\n\x0fRequestRelation\x12\x1a\n\x12\x61\x63ount_relation_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x13\n\x11RequestSmartphone\"?\n\x0fRequestTransfer\x12\x1a\n\x12\x61\x63ount_relation_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"f\n\rResponseCheck\x12\x13\n\x0bis_register\x18\x01 \x01(\x08\x12\x11\n\tis_review\x18\x02 \x01(\x08\x12\x19\n\x11master_check_user\x18\x03 \x01(\x05\x12\x12\n\nsqlite_ver\x18\x04 \x01(\x05\"\r\n\x0bResponseDmm\"\x12\n\x10ResponseRelation\"\x14\n\x12ResponseSmartphone\"\x12\n\x10ResponseTransferb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'regist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCHECK._serialized_start=42
  _REQUESTCHECK._serialized_end=56
  _REQUESTDMM._serialized_start=58
  _REQUESTDMM._serialized_end=70
  _REQUESTRELATION._serialized_start=72
  _REQUESTRELATION._serialized_end=135
  _REQUESTSMARTPHONE._serialized_start=137
  _REQUESTSMARTPHONE._serialized_end=156
  _REQUESTTRANSFER._serialized_start=158
  _REQUESTTRANSFER._serialized_end=221
  _RESPONSECHECK._serialized_start=223
  _RESPONSECHECK._serialized_end=325
  _RESPONSEDMM._serialized_start=327
  _RESPONSEDMM._serialized_end=340
  _RESPONSERELATION._serialized_start=342
  _RESPONSERELATION._serialized_end=360
  _RESPONSESMARTPHONE._serialized_start=362
  _RESPONSESMARTPHONE._serialized_end=382
  _RESPONSETRANSFER._serialized_start=384
  _RESPONSETRANSFER._serialized_end=402
# @@protoc_insertion_point(module_scope)
