# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tips.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntips.proto\x12\x08Spy.Tips\x1a\x0c\x63ommon.proto\"#\n\x0bRequestSave\x12\x14\n\x0ctips_id_list\x18\x01 \x03(\x05\"?\n\x0cResponseSave\x12/\n\x10t_user_tips_list\x18\x01 \x03(\x0b\x32\x15.Spy.Common.TUserTipsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tips_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSAVE._serialized_start=38
  _REQUESTSAVE._serialized_end=73
  _RESPONSESAVE._serialized_start=75
  _RESPONSESAVE._serialized_end=138
# @@protoc_insertion_point(module_scope)
