# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x08Spy.User\x1a\x0c\x63ommon.proto\"\'\n\x14RequestChangeComment\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\"(\n\x13RequestChangeEmblem\x12\x11\n\temblem_id\x18\x01 \x01(\x05\"*\n\x17RequestChangeFriendUnit\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\",\n\x13RequestChangeHomeBg\x12\x15\n\rbackground_id\x18\x01 \x01(\x05\",\n\x19RequestChangeHomeUnitMain\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\"+\n\x18RequestChangeHomeUnitSub\x12\x0f\n\x07unit_id\x18\x01 \x01(\x05\"!\n\x11RequestChangeName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x18RequestGetStaminaRecover\".\n\x1aRequestSetRelationPassword\x12\x10\n\x08password\x18\x01 \x01(\t\".\n\x1aRequestSetTransferPassword\x12\x10\n\x08password\x18\x01 \x01(\t\"\x17\n\x15RequestStaminaRecover\":\n\x15ResponseChangeComment\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"9\n\x14ResponseChangeEmblem\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"=\n\x18ResponseChangeFriendUnit\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"9\n\x14ResponseChangeHomeBg\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"?\n\x1aResponseChangeHomeUnitMain\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\">\n\x19ResponseChangeHomeUnitSub\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"7\n\x12ResponseChangeName\x12!\n\x06t_user\x18\x01 \x01(\x0b\x32\x11.Spy.Common.TUser\"^\n\x19ResponseGetStaminaRecover\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x1c\n\x14need_crystal_current\x18\x02 \x01(\x05\x12\x14\n\x0cneed_crystal\x18\x03 \x01(\x05\"\x1d\n\x1bResponseSetRelationPassword\"\x1d\n\x1bResponseSetTransferPassword\"z\n\x16ResponseStaminaRecover\x12.\n\rt_user_worker\x18\x01 \x01(\x0b\x32\x17.Spy.Common.TUserWorker\x12\x30\n\x0et_user_crystal\x18\x02 \x01(\x0b\x32\x18.Spy.Common.TUserCrystalb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCHANGECOMMENT._serialized_start=38
  _REQUESTCHANGECOMMENT._serialized_end=77
  _REQUESTCHANGEEMBLEM._serialized_start=79
  _REQUESTCHANGEEMBLEM._serialized_end=119
  _REQUESTCHANGEFRIENDUNIT._serialized_start=121
  _REQUESTCHANGEFRIENDUNIT._serialized_end=163
  _REQUESTCHANGEHOMEBG._serialized_start=165
  _REQUESTCHANGEHOMEBG._serialized_end=209
  _REQUESTCHANGEHOMEUNITMAIN._serialized_start=211
  _REQUESTCHANGEHOMEUNITMAIN._serialized_end=255
  _REQUESTCHANGEHOMEUNITSUB._serialized_start=257
  _REQUESTCHANGEHOMEUNITSUB._serialized_end=300
  _REQUESTCHANGENAME._serialized_start=302
  _REQUESTCHANGENAME._serialized_end=335
  _REQUESTGETSTAMINARECOVER._serialized_start=337
  _REQUESTGETSTAMINARECOVER._serialized_end=363
  _REQUESTSETRELATIONPASSWORD._serialized_start=365
  _REQUESTSETRELATIONPASSWORD._serialized_end=411
  _REQUESTSETTRANSFERPASSWORD._serialized_start=413
  _REQUESTSETTRANSFERPASSWORD._serialized_end=459
  _REQUESTSTAMINARECOVER._serialized_start=461
  _REQUESTSTAMINARECOVER._serialized_end=484
  _RESPONSECHANGECOMMENT._serialized_start=486
  _RESPONSECHANGECOMMENT._serialized_end=544
  _RESPONSECHANGEEMBLEM._serialized_start=546
  _RESPONSECHANGEEMBLEM._serialized_end=603
  _RESPONSECHANGEFRIENDUNIT._serialized_start=605
  _RESPONSECHANGEFRIENDUNIT._serialized_end=666
  _RESPONSECHANGEHOMEBG._serialized_start=668
  _RESPONSECHANGEHOMEBG._serialized_end=725
  _RESPONSECHANGEHOMEUNITMAIN._serialized_start=727
  _RESPONSECHANGEHOMEUNITMAIN._serialized_end=790
  _RESPONSECHANGEHOMEUNITSUB._serialized_start=792
  _RESPONSECHANGEHOMEUNITSUB._serialized_end=854
  _RESPONSECHANGENAME._serialized_start=856
  _RESPONSECHANGENAME._serialized_end=911
  _RESPONSEGETSTAMINARECOVER._serialized_start=913
  _RESPONSEGETSTAMINARECOVER._serialized_end=1007
  _RESPONSESETRELATIONPASSWORD._serialized_start=1009
  _RESPONSESETRELATIONPASSWORD._serialized_end=1038
  _RESPONSESETTRANSFERPASSWORD._serialized_start=1040
  _RESPONSESETTRANSFERPASSWORD._serialized_end=1069
  _RESPONSESTAMINARECOVER._serialized_start=1071
  _RESPONSESTAMINARECOVER._serialized_end=1193
# @@protoc_insertion_point(module_scope)
